### ISSUE TITLE
How to upgrade HEALPY 1.9.1

### ISSUE THREAD

**Issue by mehdirezaie** [OpenAstronomy/conda-channel#32]
Hi! the only healpy available to install for Python Anaconda is 1.9.1
which its `write_map` function breaks down. Any idea how can I install a newer version of healpy for anaconda?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mehdi/anaconda/lib/python3.6/site-packages/healpy/fitsfunc.py", line 211, in write_map
    tbhdu = pf.new_table(cols)
AttributeError: module 'astropy.io.fits' has no attribute 'new_table'
```

**Comment by bsipocz** [comment]
If a package is present on conda-forge, we tend to copy that over here to openastronomy. So I suggest to open a PR on conda-forge to do the update, otherwise you can always pip install a package even if you're in a conda environment.

**Comment by mehdirezaie** [comment]
Thanks @bsipocz !
