### ISSUE TITLE
python 2.7 build of healpy

### ISSUE THREAD

**Issue by woodmd** [OpenAstronomy/conda-channel#5]
I would like to use the healpy conda package but it looks like only builds for python 3.4/3.5 are currently available.  Would it be possible to add a build for python 2.7 as well?

**Comment by Cadair** [comment]
I see no reason why it has not uploaded a 2.7 package. @mwcraig ??

**Comment by mwcraig** [comment]
Fix is in #6

**Comment by mwcraig** [comment]
@woodmd -- python 2.7 builds should be ready soon.
